# Generated by Django 2.0.5 on 2018-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
